Name:           ros-lunar-actionlib
Version:        1.11.9
Release:        0%{?dist}
Summary:        ROS actionlib package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/actionlib
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-lunar-actionlib-msgs
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rospy
Requires:       ros-lunar-rostest
Requires:       ros-lunar-std-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-lunar-actionlib-msgs
BuildRequires:  ros-lunar-catkin >= 0.5.78
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rosnode
BuildRequires:  ros-lunar-rospy
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-std-msgs

%description
The actionlib stack provides a standardized interface for interfacing with
preemptable tasks. Examples of this include moving the base to a target
location, performing a laser scan and returning the resulting point cloud,
detecting the handle of a door, etc.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon Mar 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.11.9-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.11.8-0
- Autogenerated by Bloom

